server {
  listen 80;
  server_name haswellsecurity.com www.haswellsecurity.com;
  client_max_body_size 50M;
  location / { proxy_pass http://frontend:3000; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; }
  location /admin { proxy_pass http://cms:1337/admin; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; }
  location /api { proxy_pass http://cms:1337/api; proxy_set_header Host $host; proxy_set_header X-Real-IP $remote_addr; }
  location /uploads { proxy_pass http://cms:1337/uploads; proxy_set_header Host $host; }
}
